services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: homelab_kavita
    environment:
      - PUID=${SYSTEM_UID:-1000}
      - PGID=${SYSTEM_GID:-1000}
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ${STORAGE_BASE_DIR:-/datapool}/shares/books:/manga:ro
      - ${CONFIG_BASE_DIR:-/fastpool}/kavita/config:/kavita/config
    ports:
      - "5000:5000"
    restart: unless-stopped
