services:
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing:latest
    hostname: ${TAILSCALE_HOSTNAME:-homelab-server}-syncthing
    network_mode: host
    environment:
      - PUID=${SYSTEM_UID:-1000}
      - PGID=${SYSTEM_GID:-1000}
    volumes:
      - ${CONFIG_BASE_DIR:-/fastpool}/syncthing/config:/var/syncthing/config
      - ${STORAGE_BASE_DIR:-/datapool}/syncthing/data:/var/syncthing/data
    restart: unless-stopped
