services:
  server:
    image: gitea/gitea:1.21-rootless
    container_name: homelab_gitea
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=127.0.0.1:5433
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - /fastpool/gitea/app:/data

  db:
    image: postgres:15-alpine
    container_name: homelab_gitea_db
    network_mode: host
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${GITEA_DB_PASSWORD}
      - POSTGRES_DB=gitea
      - PGPORT=5433
    restart: unless-stopped
    volumes:
      - /fastpool/gitea/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitea -h 127.0.0.1 -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
