# /fastpool/homepage/config/services.yaml
- Core Infrastructure:
    - Gitea:
        icon: gitea.png
        href: https://homelab-staging-2.tailfb0549.ts.net:8443 # <-- Clean Secure Proxy Target
        description: Source Control Matrix
        container: homelab_gitea
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://homelab-staging-2.tailfb0549.ts.net:8444 # <-- Clean Secure Proxy Target
        description: Encrypted Secret Vault
        container: homelab_vaultwarden

- Applications:
    - Immich:
        icon: immich.png
        href: https://homelab-staging-2.tailfb0549.ts.net:8445 # <-- Clean Secure Proxy Target
        description: Photo Backup Pool
        container: immich_server
    - Syncthing:
        icon: syncthing.png
        href: https://homelab-staging-2.tailfb0549.ts.net:8384 # <-- Clean Secure Proxy Target
        description: Continuous File Sync
        container: syncthing
