services:
  samba:
    image: dperson/samba:latest
    container_name: homelab_samba
    network_mode: host
    environment:
      - TZ=${TIMEZONE:-UTC}
      - USERID=${SYSTEM_UID:-1000}
      - GROUPID=${SYSTEM_GID:-1000}
    volumes:
      - ${STORAGE_BASE_DIR:-/datapool}/shares:/storage:z
    command: -u "${SAMBA_USER};${SAMBA_PASSWORD}" -s "DataPool-Share;/storage;yes;no;no;${SAMBA_USER}"
    restart: unless-stopped
