#!/usr/bin/env bash
# modules/18_disaster_recovery/configure.sh

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../lib_utils.sh"

if [[ "${HOMELAB_ENV_LOADED:-false}" != "true" ]]; then
    source "${SCRIPT_DIR}/../../environment/staging.env"
fi

inject_nginx_routing() {
    log_info "Injecting secure reverse proxy routing for Duplicati..."
    
    cat << EOF > /fastpool/nginx/conf.d/duplicati.conf
server {
    listen 8455 ssl;
    server_name ${TAILSCALE_HOSTNAME}.${TAILSCALE_TAILNET};

    ssl_certificate /etc/nginx/certs/ts.crt;
    ssl_certificate_key /etc/nginx/certs/ts.key;

    location / {
        proxy_pass http://127.0.0.1:8200;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # Websocket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$http_connection;
    }
}
EOF

    log_info "Hot-reloading Nginx rules..."
    docker exec homelab_nginx nginx -s reload || true
}

setup_db_dump_cron() {
    log_info "Deploying nightly database export cron job..."
    local cron_script="/etc/cron.daily/homelab_db_dump"
    
    cat << 'EOF' > "${cron_script}"
#!/usr/bin/env bash
# Auto-generated by FedoraForge Disaster Recovery Module
# Dumps active Postgres/MySQL databases to static files before Duplicati backup.

echo "Exporting Immich database..."
docker exec immich_postgres pg_dump -U postgres immich > /datapool/backups/db_dumps/immich_db_backup.sql || true

# Add additional database dumps here as your homelab grows
EOF

    chmod +x "${cron_script}"
}

launch_service() {
    log_info "Wiping stale instances of Duplicati..."
    cd "${SCRIPT_DIR}/compose"
    docker compose down 2>/dev/null || true

    log_info "Launching Duplicati Disaster Recovery engine..."
    export TIMEZONE CONFIG_BASE_DIR STORAGE_BASE_DIR SYSTEM_UID SYSTEM_GID
    
    docker compose up -d --force-recreate || exit 1
    log_succ "Duplicati deployed successfully!"
}

# Execute
inject_nginx_routing
setup_db_dump_cron
launch_service
